### PR TITLE
Implement HTTP support

### LINKED ISSUE #26: Add a client for HTTP downloads
Add a client based on hyper.

### PR DESCRIPTION
**Pull request by nyurik**
This is a first (working) pass at implementing HTTP support for Condow, following up the #35 discussion.

## Notable Changes
* `http_status_to_error` has been moved to core -- too complex to maintain in every client

## TODO

- [ ] Tests
- [ ] Documentation
- [ ] Examples
- [ ] Clean up changelog (why are they all the same? shouldn't there be just one in the root?)

It uses a crate I had to create for it -- [http-content-range](https://github.com/nyurik/http-content-range) to parse content-range headers.

Closes #26

### CODE REVIEW

**Comment by nyurik** [comment]
@chridou what would be the next steps here?  Are you ok with this approach?  Let me know how we can proceed. Thx!

**Comment by chridou** [comment]
@nyurik, I am perfectly fine with this approach. I'll answer on the API discussion now.

The reason why there are multiple changelogs (one for each crates) is that I wanted to version them independently.

**Comment by nyurik** [comment]
Hi @chridou , what do you think should be our next steps with the API and http downloader?  Thx!

**Comment by chridou** [comment]
@nyurik After we removed the ugly logging we should continue with the API. I would also like to get rid of the generic `Reporter` parameter first. I think we do not call it too often and we are dealing with IO anyways so we could make it `Arc<dyn>`.

**Comment by chridou** [comment]
I think we could merge this so that we have an HTTP download for now. There will be a lot of upcoming breaking changes anyways...

**Pull request merged**
